# Generated by Django 5.0.4 on 2024-04-24 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 24, 15, 17, 17, 822827), null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('analise', 'Em analise'), ('deferido', 'Deferido')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
