# Generated by Django 5.0.4 on 2024-04-24 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crur', '0002_register_date_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 24, 15, 23, 6, 540746), null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('analise', 'Em analise'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido')], max_length=100),
        ),
    ]
