# Generated by Django 5.0.4 on 2024-04-24 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crur', '0003_register_response_alter_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 24, 15, 26, 57, 183653), null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('analise', 'Em analise'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido')], default='analise', max_length=100),
        ),
    ]
