# Generated by Django 5.0.4 on 2024-04-25 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crur', '0004_alter_register_date_alter_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Identificador do Arquivo'),
        ),
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 25, 13, 8, 48, 230197), null=True),
        ),
    ]
