# Generated by Django 5.0.4 on 2024-04-25 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crur', '0005_archive_name_alter_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 25, 14, 47, 2, 732072), null=True),
        ),
    ]
