# Generated by Django 5.0.4 on 2024-05-03 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crur', '0006_alter_register_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_contact', models.CharField(max_length=200, verbose_name='Numero para receber solicitações')),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 12, 34, 50, 504293), null=True),
        ),
    ]
