# Generated by Django 5.0.4 on 2024-05-15 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crur', '0010_alter_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive',
            field=models.FileField(upload_to='crur/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 15, 10, 31, 8, 644240), null=True),
        ),
    ]
