# Generated by Django 5.0.4 on 2024-05-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crur', '0014_alter_register_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
