# Generated by Django 5.0.4 on 2024-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crur', '0015_rename_settings_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='response_attachments',
            field=models.ManyToManyField(related_name='register_response_attachments', to='crur.archive'),
        ),
        migrations.AlterField(
            model_name='register',
            name='archives',
            field=models.ManyToManyField(related_name='register_archives', to='crur.archive'),
        ),
    ]
